/**
 * This file is auto-generated by openapi-typescript.
 * Do not make direct changes to this file.
 * Run `pnpm generate` in the types package to regenerate.
 * 
 * The backend must be running for generation to work.
 * Backend Swagger endpoint: http://localhost:3000/swagger/json
 */

// This will be overwritten by the generation script
export interface paths {}
export interface components {}
export interface operations {}
