import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "./v1"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_HOST,
  credentials: "include",
});

const authMiddleware: Middleware = {
  async onResponse({ request, response }) {
    // If unauthorized, attempt to refresh the token
    if (response.status === 401 && !request.url.includes("/auth/refresh")) {
      const { response: refreshResponse } = await client.POST("/auth/refresh");
      if (refreshResponse.ok) {
        // Token refreshed successfully, retry the original request
        const retryResponse = await fetch(request.url, {
          method: request.method,
          headers: request.headers,
          body: request.body,
          credentials: "include",
        });

        return retryResponse;
      } else {
        // If refresh fails, redirect to signIn (only in browser)
        if (typeof window !== 'undefined') {
          window.location.href = "/?status=401&action=signIn";
        }
      }
    }
    // Return the original response if not 401 or refresh failed
    return response;
  },
};

client.use(authMiddleware);

export default client;
